In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sklearn
import os 
from sklearn.model_selection import GridSearchCV, train_test_split

In [2]:
df = pd.read_csv(r'C:\Users\Aizen Freecs\Downloads\Luflow_Project\Train\LUFlow.csv')

In [3]:
df["label"].value_counts()

malicious    1405066
benign       1405066
Name: label, dtype: int64

In [4]:

df.head(100)

,avg_ipt,bytes_in,bytes_out,dest_ip,dest_port,entropy,num_pkts_out,num_pkts_in,proto,src_ip,src_port,time_end,time_start,total_entropy,label,duration
0,0.0,0,0,786,4231.0,0.000000,1,1,6,207812,41228.0,1592533714967956,1592533714967956,0.0000,malicious,0.000000
1,0.0,0,0,786,48648.0,0.000000,1,1,6,50340,42166.0,1592533737529803,1592533737529803,0.0000,malicious,0.000000
2,0.0,0,0,786,22884.0,0.000000,1,1,6,38365,55874.0,1592533701107675,1592533701107675,0.0000,malicious,0.000000
3,0.0,0,0,786,5457.0,0.000000,1,1,6,206728,42810.0,1592533764353983,1592533764353983,0.0000,malicious,0.000000
4,0.0,0,0,786,1235.0,0.000000,1,1,6,206728,43538.0,1592533783515817,1592533783515817,0.0000,malicious,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,140.0,299,90,786,1900.0,5.518981,1,1,17,4837,6803.0,159253416578273,1592534165501847,2146.8838,malicious,0.280883
96,132.5,299,90,786,1900.0,5.518981,1,1,17,4837,14409.0,1592534166120472,1592534165855419,2146.8838,malicious,0.265053
97,200.0,299,90,786,1900.0,5.518981,1,1,17,4837,37332.0,1592534165919465,159253416551872,2146.8838,malicious,0.400745
98,179.5,299,90,786,1900.0,5.518981,1,1,17,4837,44890.0,1592534167089675,1592534166730556,2146.8838,malicious,0.359119
99,203.0,299,90,786,1900.0,5.518981,1,1,17,4837,8164.0,1592534166461624,159253416605506,2146.8838,malicious,0.406564

In [6]:
old_value = 'malicious'
new_value = 1
df['label'] = df['label'].replace(old_value, new_value)
old_value = 'benign'
new_value = 0
df['label'] = df['label'].replace(old_value, new_value)

In [7]:
train, test = train_test_split(df, test_size=0.3)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2810132 entries, 0 to 2810131
Data columns (total 16 columns):
 #   Column         Dtype
---  ------         -----
 0   avg_ipt        float64
 1   bytes_in       int64
 2   bytes_out      int64
 3   dest_ip        int64
 4   dest_port      float64
 5   entropy        float64
 6   num_pkts_out   int64
 7   num_pkts_in    int64
 8   proto          int64
 9   src_ip         int64
 10  src_port       float64
 11  time_end       int64
 12  time_start     int64
 13  total_entropy  float64
 14  label          int64
 15  duration       float64
dtypes: float64(6), int64(10)
memory usage: 343.0 MB

In [9]:
# function to save the cleaned dataset
def save_cleaned_dataset(dataframe: pd.DataFrame,dataset: str, tag: str = ""):
    # create a new directory to save the cleaned dataset
    os.makedirs('./Dataset/dataset_final', exist_ok=True)

    if not(tag == ""):
        tag = "_" + tag

    dataframe.to_csv(f'Dataset/dataset_final/{dataset}{tag}.csv', index=False)

In [10]:
save_cleaned_dataset(dataframe=train, dataset='LUFlow_Train')
save_cleaned_dataset(dataframe=test, dataset='LUFlow_Test')

In [12]:
df.head(400)

,avg_ipt,bytes_in,bytes_out,dest_ip,dest_port,entropy,num_pkts_out,num_pkts_in,proto,src_ip,src_port,time_end,time_start,total_entropy,label,duration
0,0.0,0,0,786,4231.0,0.000000,1,1,6,207812,41228.0,1592533714967956,1592533714967956,0.0000,1,0.000000
1,0.0,0,0,786,48648.0,0.000000,1,1,6,50340,42166.0,1592533737529803,1592533737529803,0.0000,1,0.000000
2,0.0,0,0,786,22884.0,0.000000,1,1,6,38365,55874.0,1592533701107675,1592533701107675,0.0000,1,0.000000
3,0.0,0,0,786,5457.0,0.000000,1,1,6,206728,42810.0,1592533764353983,1592533764353983,0.0000,1,0.000000
4,0.0,0,0,786,1235.0,0.000000,1,1,6,206728,43538.0,1592533783515817,1592533783515817,0.0000,1,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,415.5,299,90,786,1900.0,5.518981,1,1,17,4837,56920.0,1592534172521155,159253417168965,2146.8838,1,0.831505
396,545.5,299,90,786,1900.0,5.518981,1,1,17,4837,59731.0,1592534172311898,1592534171219937,2146.8838,1,1.091961
397,580.0,299,90,786,1900.0,5.518981,1,1,17,4837,43542.0,1592534172387418,159253417122673,2146.8838,1,1.160688
398,441.0,299,90,786,1900.0,5.518981,1,1,17,4837,11359.0,1592534172590336,1592534171708161,2146.8838,1,0.882175
399,392.5,299,90,786,1900.0,5.518981,1,1,17,4837,38635.0,1592534170428919,1592534169643082,2146.8838,1,0.785837